spring.application.name=Raging-Horse-Tetris-4-1
shotsPath=\\src\\main\\resources\\static\\shots\\
mongoPrepareShotsPath=\\src\\main\\resources\\static\\mongoPrepareShots\\

app.base-url=${BASE_URL:http://localhost:5555}

eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka
eureka.instance.leaseRenewalIntervalInSeconds=5

management.endpoints.web.exposure.include=*

width=12
height=20

server.forward-headers-strategy=framework
spring.threads.virtual.enabled=true

# --- НАСТРОЙКА gRPC КЛИЕНТА ---

# БЫЛО:
# grpc.client.mongo-service.address=discovery:///mongo-service

# Возвращаем поиск через Eureka
grpc.client.mongo-service.address=discovery:///mongo-service

# Магический флаг: заставляет клиента искать порт в метаданных (ключ 'grpc.port')
grpc.client.mongo-service.discovery-stub=true

grpc.client.mongo-service.negotiation-type=plaintext

# Время ожидания (10 секунд — отлично для скриншотов)
grpc.client.mongo-service.deadline=10s

# Размер сообщения (10 МБ)
grpc.client.mongo-service.max-inbound-message-size=10485760

# Дополнительные настройки для стабильности
grpc.client.mongo-service.shared=false
# --- НАСТРОЙКА gRPC КЛИЕНТА ДЛЯ GAME-SERVICE ---

# Указываем имя, которое мы использовали в @GrpcClient("game-service")
grpc.client.game-service.address=discovery:///game-service
grpc.client.game-service.discovery-stub=true

# ВОТ ЭТА СТРОКА РЕШИТ ОШИБКУ HTTP/2 Preface:
grpc.client.game-service.negotiation-type=plaintext

grpc.client.game-service.deadline=5s
